name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Generate Environment Variables File
        run: |
          echo "REACT_APP_MAIL_CLIENT_ID=$MAIL_CLIENT_ID" >> .env.production
          echo "REACT_APP_MAIL_CLIENT_PW=$MAIL_CLIENT_PW" >> .env.production
          echo "REACT_APP_MAIL_DESTINATION=$MAIL_DESTINATION" >> .env.production
          echo "REACT_APP_SMTP_HOST=$SMTP_HOST" >> .env.production
          echo "REACT_APP_SMTP_PORT=$SMTP_PORT" >> .env.production
        env:
          MAIL_CLIENT_ID: ${{ secrets.MAIL_CLIENT_ID }}
          MAIL_CLIENT_PW: ${{ secrets.MAIL_CLIENT_PW }}
          MAIL_DESTINATION: ${{ secrets.MAIL_DESTINATION }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}

      - name: Install Dependencies and Surge
        run: |
          npm install
          npm install surge --global

      - name: Build React Application
        run: npm run build

      - name: Deploy React Application to Surge
        run: surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
